# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_wagomu', [dirname(__file__)])
        except ImportError:
            import _wagomu
            return _wagomu
        if fp is not None:
            try:
                _mod = imp.load_module('_wagomu', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _wagomu = swig_import_helper()
    del swig_import_helper
else:
    import _wagomu
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Character(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Character, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Character, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wagomu.new_Character(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wagomu.delete_Character
    __del__ = lambda self : None;
    def get_points(self): return _wagomu.Character_get_points(self)
    def get_n_vectors(self): return _wagomu.Character_get_n_vectors(self)
    def get_n_strokes(self): return _wagomu.Character_get_n_strokes(self)
    def set_value(self, *args): return _wagomu.Character_set_value(self, *args)
Character_swigregister = _wagomu.Character_swigregister
Character_swigregister(Character)

class Results(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Results, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Results, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _wagomu.new_Results(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wagomu.delete_Results
    __del__ = lambda self : None;
    def get_unicode(self, *args): return _wagomu.Results_get_unicode(self, *args)
    def get_distance(self, *args): return _wagomu.Results_get_distance(self, *args)
    def get_size(self): return _wagomu.Results_get_size(self)
Results_swigregister = _wagomu.Results_swigregister
Results_swigregister(Results)

class Recognizer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Recognizer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Recognizer, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _wagomu.new_Recognizer()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _wagomu.delete_Recognizer
    __del__ = lambda self : None;
    def open(self, *args): return _wagomu.Recognizer_open(self, *args)
    def recognize(self, *args): return _wagomu.Recognizer_recognize(self, *args)
    def get_n_characters(self): return _wagomu.Recognizer_get_n_characters(self)
    def get_dimension(self): return _wagomu.Recognizer_get_dimension(self)
    def get_window_size(self): return _wagomu.Recognizer_get_window_size(self)
    def set_window_size(self, *args): return _wagomu.Recognizer_set_window_size(self, *args)
    def get_error_message(self): return _wagomu.Recognizer_get_error_message(self)
Recognizer_swigregister = _wagomu.Recognizer_swigregister
Recognizer_swigregister(Recognizer)

# This file is compatible with both classic and new-style classes.


